### ISSUE TITLE
Add the input for GitHub action to specify release message pattern

### ISSUE THREAD

**Issue by alexey-igrychev** [googleapis/release-please#1039]
Currently, there is no way to change the release message.
Thus, the user cannot add static text before/after changelog or use bumped version anyhow.

It seems to me a template with variables could help many users. E.g.:
```
- uses: GoogleCloudPlatform/release-please-action@v2
  with:
    release-type: node
    package-name: release-please-action
    release-message: |
      The community keeps growing, and we'd love to see you there!

      - Link to slack
      - Link to tg
      - Link to twitter

      ## Installation

      Download [here](https://storage.com/release/v${VERSION}/app.tar.gz).

      ## Changelog

      ${CHANGELOG}
```
