### ISSUE TITLE
bug: opam support currently doesn't update `project.opam.locked` files

### ISSUE THREAD

**Issue by erikmd** [googleapis/release-please#1085]
First, thanks for developing and maintaining this very nice tool!

#### Environment details

  - OS: GNU/Linux and GitHub Actions
  - Node.js version: N/A
  - npm version: N/A
  - release-please version: `GoogleCloudPlatform/release-please-action@v2`
  - release-type (language): ocaml

#### Steps to reproduce

  1. Use a GHA workflow similar to the snippet below (in an **ocaml/opam**-based GitHub project)
  2. Do some action to automatically bump the version number (actually, anything that will open a Release PR)
  3. Notice that release-please will only update the version string in `dune-project` and `*.opam` versions,  
  but **not** in `*.opam.locked` files (while that looked some expected feature IMHO, a bit like `package-lock.json` support)

```yaml
jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      body: ${{ steps.release.outputs.body }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ocaml
          package-name: learn-ocaml
          bump-minor-pre-major: true
```

#### Additional details

I believe it would suffice to reuse the `opam.ts` updater as is, and add support for `opam.locked` file extension by copying this snippet in `ocaml.ts` releaser?

https://github.com/googleapis/release-please/blob/9850c20a7d0dce0d6ca0b14c9cc45d41752f36fc/src/releasers/ocaml.ts#L57-L67

FTR, [this man page](https://opam.ocaml.org/doc/man/opam-lock.html) documents these `*.opam.locked` files.

(Let me know if you'd need more details, or tests)
