### ISSUE TITLE
Add a generic script-based release strategy

### ISSUE THREAD

**Issue by raphink** [googleapis/release-please#1139]
It would be useful to be able to launch a custom script from the GitHub repo to update specific files without having to create a new type of release strategy in release-please.

Something like:

```
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: exec
           command: update-my-files.sh
```

The script would then receive the version number as parameter and be able to perform actions on the repository before release-please commits the files to the branch.
