### ISSUE TITLE
Cargo.toml not updated for rust workspaces

### ISSUE THREAD

**Issue by jcornaz** [googleapis/release-please#1170]
#### Environment details

  - OS: ubuntu-latest (Running on github actions)
  - Node.js version: -
  - npm version: -
  - `release-please` version: `GoogleCloudPlatform/release-please-action@v2.35.0`

#### Steps to reproduce

1. Create a simple rust project: 

```sh
cargo new release-please-issue-1170
cd release-please-issue-1170
cargo new sub-crate
```

2. Make it a workspace by a adding to the root `Cargo.toml`:

 ```toml
[workspace]
members = ["sub-crate"]
 ```

3. Write `.github/workflows/release.yml`:

```yaml
name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: rust
```

4. Commit,tag `v0.1.0` and push to a github repo.

5. Commit (and push) a "feature": `git commit -m "feat: New shiny feature"' --allow-empty`
6. Observe the created PR. The two `Cargo.toml` are not updated! (Only the `Cargo.lock` is)
