### ISSUE TITLE
Add ability to update arbitrary JSON files

### ISSUE THREAD

**Issue by goatwu1993** [googleapis/release-please#1171]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**

I would like to have an arbitrary file updater.

This updater should be able to replace content from a version to another, without any extra regex.

For example, replace all 0.1.0 to 0.2.0 in a file

**Comment by chingor13** [comment]
I'm going to repurpose this issue to track the ability to update arbitrary JSON. The generic file updater in #1157 should handle most files except JSON which does not allow for comments.

**Comment by axieum** [comment]
_Moved comment from #1168._

Perhaps the generic updaters (#1157) could take a replacement `method`, e.g.

```jsonc
{
  "extra-files": [
    {
      "path": "version.json",
      "method": "regex",
      "version": ["\"version\": \"(.+?)\""], // arg for full version
      "minor": ["\"minor\": \"(.+?)\""] // arg for minor, can add more for major, patch, build, etc.
    },
    {
      "path": "some.txt",
      "method": "annotation" // optional/default
    },
    {
      "path": "other.json",
      "method": "json",
      "major": "version.items[2].major" // arg for major
  ]
}
```

I'm not sure how this would be set on the CLI though if wanting to allow configuration through that as well?

**Comment by goatwu1993** [comment]
My first thought is to have an updater which takes file path and jmespath as input.

Whether use extra files or another key is discussable. Personally iI would suggest to use another key. Extrafiles use generic updater and another input (say ExtraJsonKeys) use the JMES updater.

**Comment by goatwu1993** [comment]
A crazier thought: User can write a script in their repo. An updater to run these script and pass the version number as argument.

**Comment by axieum** [comment]
> A crazier thought: User can write a script in their repo. An updater to run these script and pass the version number as argument.

This would've made part of #1139.

**Comment by rabraghib** [comment]
any updates on this?

**Comment by rabraghib** [comment]
Maybe having the `extraFiles` option accept an array of strings as well as objects will solve the problem
An object that indicates which updater to use??

https://github.com/googleapis/release-please/blob/main/src/strategies/base.ts#L292

**Comment by joeyparrish** [comment]
This would be a very useful feature for Chrome extensions, which have their version number in `manifest.json`.

**Comment by joeyparrish** [comment]
I came up with a work-around in GitHub Actions, if anyone is interested.  It uses `jq` to modify the Chrome extension's `manifest.json` file that release-please won't touch, and extracts the correct version number from `package.json` to do so.

```yaml
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v2

      # If we didn't create a release, we may have created or updated a PR.
      - run: |
          # Check out the branch that release-please created, if it exists.
          git fetch
          git checkout release-please--branches--main || exit 0
          # If it does exist, update manifest.json in the PR branch.
          # release-please can't update it for us yet.  See:
          # https://github.com/googleapis/release-please/issues/1171
          VERSION=$(jq -r .version package.json)
          cp manifest.json manifest.json.orig
          jq -r ".version = \"$VERSION\"" manifest.json.orig > manifest.json
          git add manifest.json
          # Emulate the author of the existing commit (the bot).
          git config user.email "$(git log -n 1 --format='%ae')"
          git config user.name "$(git log -n 1 --format='%an')"
          # Update the PR.
          git commit --amend --no-edit
          git push -f
        if: ${{ ! steps.release.outputs.release_created }}
```

To adapt this to your own workflows, take note that the destination branch name is involved in the PR branch (`release-please--branches--main`, for example).  In the snippet below, I'm hard-coding that.  You may also want to change `manifest.json` or the `.version` query I'm using to update the contents with `jq`.

My full workflow is here: https://github.com/google/eme_logger/blob/main/.github/workflows/release-please.yml

I hope this helps!
