### ISSUE TITLE
python release type not able to find correct python packages when using poetry

### ISSUE THREAD

**Issue by goatwu1993** [googleapis/release-please#1229]
**Is your feature request related to a problem? Please describe.**

When using poetry and package name contains dash, python release type not able to find correct version files 

 **Describe the solution you'd like**

Have a better guess by replacing dash with an underscore.

For example, I have a pyproject.toml

```toml
[tool]

[tool.poetry]
name = "my-service-client"
version = "0.1.0"
description = ""
```

Release please warn me
```bash
file my-service-client/__init__.py did not exist
```

while is file path is actually `my_service_client/__init__.py`

 **Describe alternatives you've considered**

Package name and extra files should be able to bump the file correctly, however guessing the package name better is always something nice to have.
