### ISSUE TITLE
Can we allow 'docs' to trigger a release and be in the changelog?

### ISSUE THREAD

**Issue by dwmkerr** [googleapis/release-please#1312]
The current front page of the repo notes:

> Some languages have their specific releasable unit configuration. For example, "docs" is a prefix for releasable units in Java and Python.

I have a Javascript based project which is a book:

https://github.com/dwmkerr/effective-shell

I would *love* it if `docs` could trigger a release _and_ the docs changes could be in the changelog - I tried to find if there's a way to configure this but not sure if I can. Am I missing something silly?

Thanks in advance friends! CC @tobiasbueschel

**Comment by chingor13** [comment]
You should be able to configure `changelogSections`. Anything that is visible in the changelog is considered releaseable and will trigger a patch version bump (except `feat` and breaking changes).

**Comment by dwmkerr** [comment]
@chingor13 this sounds perfect - I've searched the docs for anything on how to do this but can't find it - do you have an example? I am then more than happy to PR and update into the docs!

**Comment by dwmkerr** [comment]
@chingor13 I tried this but no luck - any ideas? Sorry to bother - when I get it working I will update the docs!

```yaml
name: Release Please
on:
  push:
    branches:
      - main
      - build/test-documentation-in-changelog
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: Guild Handbook
          # We include 'docs' in the changelog types, this means document
          # changes will be in the CHANGELOG and also that docs changes will
          # trigger a patch release. This is essential as we basically are
          # primarily docs project.
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"docs","section":"Documentation","hidden":false},
            {"type":"deps","section":"dependencies","hidden":true},
            {"type":"chore","hidden":true}]
            # ...
```

**Comment by dwmkerr** [comment]
Ugh, ignore this - I think the docs describe this here:

https://github.com/google-github-actions/release-please-action/commit/2ca6d30396e3b6b10ca9623ecbc3174b476ec8a2

Testing now, if it works I'll link this repo to the docs above and close, sorry

**Comment by dwmkerr** [comment]
For those reviewing this issue in the future, to add `docs` as something that is released, update the action to look like this:

```yaml
name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: My Package
          # We include 'docs' in the changelog types, this means document
          # changes will be in the CHANGELOG and also that docs changes will
          # trigger a patch release. This is essential as we basically are
          # primarily docs project.
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false}]'
```

This is described in the documentation at:

https://github.com/google-github-actions/release-please-action#overriding-the-changelog-sections
