### ISSUE TITLE
Expose pom updater to extraFiles

### ISSUE THREAD

**Issue by mdvorak** [googleapis/release-please#1480]
I have feature request from a colleague, they want to release maven app, but they don't want to use snapshots. That is valid request, and while it is possible to do that with `simple` strategy and `extraFiles`, it is quite cumbersome - xml updater needs complex xpath, and generic is error-prone.
This I suggest exposing already present `PomXml` updater (used by maven strategy), to be usable in `extraFiles`, just like others.

`release-please.yml` [bot] for such case would then look like:
```yaml
releaseType: simple
extraFiles:
  - type: pom
    path: pom.xml
  - type: pom
    path: submodule/pom.xml
```
