### ISSUE TITLE
Enabling "skip-github-release" causes release-please to break after merging the release PR

### ISSUE THREAD

**Issue by taisph** [googleapis/release-please#1561]
#### Environment details

  - OS: GitHub Actions/ubuntu-latest
  - `release-please` version: 13.19.6 (via release-please-action@v3)

#### Steps to reproduce

  1. Bootstrap release-please in a new repo and add the release-please GitHub action with command: manifest.
  2. Change manifest config to enable "skip-github-release" for the root package.
  3. Make commits to trigger a release PR.
  4. Merge the release PR (tested with squash and rebase). The "autorelease" label doesn't change effectively stopping release-please from working with the error: 
  ⚠ There are untagged, merged release PRs outstanding - aborting

**Comment by chingor13** [comment]
The `skip-github-release` option only absolves `release-please` of its duty to create GitHub releases/tags. If you do not create GitHub releases, `release-please` will have difficulty determining the SHA of the latest release (from which to consider commits for the next release).

That option was built for folks that already had mechanisms for tagging releases.

Can you elaborate on your use case for skipping the release?

**Comment by taisph** [comment]
We don't use GitHub releases but do use annotated Git tags to mark a release. The assumption of "skip-github-release" was that it would not create a GitHub release but still create a Git tag. If release-please needs actual GitHub releases to function as opposed to a Git tag, then I guess we're stuck with that. I just find it odd that it can so easily end up in a non-functional state.

**Comment by kojiromike** [comment]
Our workaround for this is the obviously-racy act of immediately clobbering the lightweight tag. I don't have this in a public repo right now, so I'll share it here for now. Honestly, it's not great, but either it's the best we've got or someone will hopefully post something better.

```yaml
    # Convert lightweight tag to annotated tag
    #
    # Why this is needed:
    # - Release-please creates releases via GitHub's release API, which creates lightweight tags
    # - We require annotated tags because:
    #   * git describe ignores lightweight tags by default (requires --tags flag)
    #   * Lightweight tags are not copied into forks
    #   * Annotated tags have proper metadata (creation date, tagger info, message)
    #
    # Why we do this after release creation:
    # - We can't create the annotated tag before release-please runs because we don't know
    #   the version number until release-please determines it from conventional commits
    # - The GitHub release API will use an existing tag if present (per the target_commitish
    #   parameter docs: "Unused if the Git tag already exists"), but release-please doesn't
    #   provide a way to hook into the process between version determination and release creation
    # - Using skip-github-release has known issues and breaks release-please's workflow
    #   (see: https://github.com/googleapis/release-please/issues/1561)
    #
    # Race condition considerations:
    # - There is a small window (milliseconds) between when the lightweight tag is created
    #   and when we convert it to annotated where someone could fetch the lightweight tag
    # - In practice, this risk is acceptable because:
    #   * Most users interact with releases, not tags directly
    #   * The window is extremely brief
    #   * By the time manual tag fetches occur, the annotated version exists
    #   * The GitHub release points to the correct commit regardless of tag type
    - name: Convert to annotated tag
      if: ${{ steps.release.outputs.release_created }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch --tags
        TAG_NAME="${{ steps.release.outputs.tag_name }}"
        git tag -a -f -m "Release ${TAG_NAME}" "${TAG_NAME}" "${TAG_NAME}^{commit}"
        git push -f origin "${TAG_NAME}"
```
