### ISSUE TITLE
gh action: `Warning: Unexpected input(s) 'bootstrap-sha'`

### ISSUE THREAD

**Issue by tmillr** [googleapis/release-please#1592]
## What you're trying to do

Setup the gh action with my basic single-module/package node repo.

I'd like the changelog to include all previous releases that I've
made manually, so I've set `bootstrap-sha` to the root commit
(although this doesn't seem to be working).

## What code you've already tried

```yaml
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          bootstrap-sha: dd466e8d671cb8ec55b39767624c775acfdfc63d

```

## Any error messages you're getting

```
Warning: Unexpected input(s) 'bootstrap-sha', valid inputs are ['token', 'fork', 'clean', 'package-name', 'release-type', 'bump-minor-pre-major', 'bump-patch-for-minor-pre-major', 'path', 'changelog-path', 'command', 'version-file', 'extra-files', 'default-branch', 'changelog-types', 'config-file', 'manifest-file', 'signoff', 'github-api-url', 'github-graphql-url', 'repo-url', 'monorepo-tags', 'pull-request-title-pattern', 'draft', 'draft-pull-request']
```

Do I have to use the manifest release to get this behavior? 
I just opted for the most straightforward setup/config since 
my repo is so simple and I thought it might be better not to
add any unnecessary config files. Thanks
