### ISSUE TITLE
How does release-please work out which release is the "previous" release? 

### ISSUE THREAD

**Issue by jwalton** [googleapis/release-please#1687]
How does release-please work out which release is the "previous" release? 

I know semantic-release analyzses git tags, but there doesn't seem to be any information in release-please's documentation about where it gets the previous version from.

I ask because I currently have a node.js project I'm converting from semantic-release to release-please, but the release PR created has a bunch of extra stuff in it from several previous releases, so somehow release-please is misidentifying the previous release.  The previous release is tagged as v2.0.2, there's a release for v2.0.2, the package.json says 2.0.2, but there's changes in the release-please PR from well before v2.0.2.

**Comment by jwalton** [comment]
Ah, the [docs say](https://github.com/googleapis/release-please#bootstrapping-your-repository):

> Release Please looks at commits since your last release tag. It may or may not be able to find your previous releases.

What does that mean?  Is a "release tag" a tag associated with a release in GitHub?

**Comment by jwalton** [comment]
OK, I'm going to further complicate this question:

We're using the release-please github action:

```
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          
      snip
          
      - name: Publish Package
        run: npm publish
        if: ${{ steps.release.outputs.release_created }}          
```

The previous release was 2.0.2, we added release-please, it tried to generate a release 2.1.0 PR that everything correct in it.  We merged that PR, but then the publish failed.  We "unwound" the work release-please did by deleting the release and the tag, then we fixed our permission problem, and re-ran release please, and the new PR had all this extra stuff in it.

It looks like release-please is trying to find all releases more recent than 2.1.0.  The PR it generates has a compare link that compares 2.1.0, which is a tag that doesn't exist.  Where is it getting 2.1.0 from when the tag and release have both been deleted?
