### ISSUE TITLE
On push to branch X, crease release to branch Y, how?

### ISSUE THREAD

**Issue by ale8k** [googleapis/release-please#1697]
Hi, I'm trying to use release-please to automate releases, but I think I may be misunderstanding the use case and would like to clarify.

I was going to file this on the action repo, but there's no question type issue. 

Our workflow is: 
1. Fork repo
2. Feature branch (all commits are conventional within this branch)
3. Create PR against development branch
4. Merge to develop branch via rebase so that the commits persist their conventional style

At this point, I would like the release-please action to automate these release PRs to our main branch. The release-please action isn't picking up on these commits though or proposing a PR to our main branch. 

I've then added the action as so:
```yaml
name: release-please-test

on:
  push:
    branches:
      - development

jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          default-branch: main
          include-v-in-tag: false
```

It is indeed triggering the workflow, but with the output:

````
Run google-github-actions/release-please-action@v3
✔ Looking for latest release on branch: main with prefix: release-please-action
✔ Building releases
✔ Building strategies by path
✔ Looking for latest release on branch: main with prefix: release-please-action
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
✔ Collecting commits since all latest releases
✔ PR #793 has many files, backfilling
✔ Splitting 12 commits by path
✔ Building candidate release pull request for path: .
✔ Considering: 0 commits
✔ No commits for path: ., skipping

```

Again, I think I'm maybe misunderstanding at in many of the examples the push event and default-branch are the same. Any help is greatly appreciated!

Thanks
