### ISSUE TITLE
How to update version in the __init__.py when releasing next to updating pyproject.toml?

### ISSUE THREAD

**Issue by mpas** [googleapis/release-please#1741]
Currently i am releasing a python project with a pyproject.toml.

```
[tool.poetry]
version = "0.0.1"
```

Is it possible to also reflect that release number in the __init__.py so people can check what version they are using?

I tried to put a placeholder in the format:

```
file: __init__.py inside my package
__version__ = "0.0.0"
```

**Comment by kai-tub** [comment]
Hey, I can provide you with a workaround if you are using Python >=3.8.
You can use [importlib.metadata](https://docs.python.org/3.8/library/importlib.metadata.html), and then you also have a single source of truth and don't have to worry about synchronizing these two values.

```python
import importlib.metadata

__version__ = importlib.metadata.version("<YOUR_PACKAGE_NAME>")
```

The value will be identical to the one given in `pyproject.toml`

**Comment by kelvindecosta** [comment]
Hey @kai-tub 

Thanks for this!

I made a slight modification:

```python
# Inside src/project/__init__.py
__version__ = importlib.metadata.version(__name__)
```

**Comment by kai-tub** [comment]
@kelvindecosta 
Thanks for letting me know the updated version!
I completely forgot that this was an option!
I will have to update a few packages now :D

**Comment by dmi3y** [comment]
Alternatively use `x-release-please-version` for updating arbitrary files e.g.

inside `__init__.py`:
```python
__version__='1.0.0' # {x-release-please-version}
```

And via add it as extra file via config or I'm adding it via action config.
inside `.github/workflows/release-please.yml`, tweak it accordingly.
```yml
on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          extra-files: |
            project_x/__init__.py
```
