### ISSUE TITLE
`default-branch` usage

### ISSUE THREAD

**Issue by pbahng** [googleapis/release-please#1751]
Pretty much the same as this closed issue, https://github.com/googleapis/release-please/issues/1697 but maybe I'm not understanding `default-branch`'s usage.

I'd like the release PR to raise against a branch that's different than the `on: push: branches: <branch>` defined at the top of the workflow file. The initial issue linked above is explaining that the workflow was looking for changes in `main` branch which he set as the `default-branch` (which the documentation explains is the appropriate place for release PRs to be made) and not in `development` branch where the commits are to be tracked.

<img width="832" alt="Screen Shot 2022-11-14 at 3 05 03 PM" src="https://user-images.githubusercontent.com/105989817/201755031-059b66af-466c-4eeb-b6b4-d4c57b9064a4.png">

 In my opinion this is not a branch management issue, are we simply not able to target a different branch for the release PR to be made? Are these innately the same thing?

Here's my workflow file for reference:

```
on:
  push:
    branches:
      - main // <- Expecting for conventional commits to be tracked here
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: node
          package-name: release-please-action
          default-branch: production // <- Expecting for release PR to be made to this branch
```
