### ISSUE TITLE
Add GemfileLock updater to bump version in Gemfile.lock for Ruby

### ISSUE THREAD

**Issue by andrewthauer** [googleapis/release-please#1768]
**Is your feature request related to a problem? Please describe.**

I'm trying to use `release-please` with Ruby gems that have `Gemfile.lock` committed. The newest official recommendation for this is to commit the lock file (see [Should I commit my `Gemfile.lock` when writing a gem?](https://bundler.io/guides/faq.html#using-gemfiles-inside-gems) in the official `bundler` FAQ). Typically you run `bundle install` after a `version.rb` bump which updates a line at the top of the lock file indicating the new version. However, this `release-please` currently does not do this so CI steps can fail to proceed as the lock file is out of date.

 **Describe the solution you'd like**
 
 I'd like to add a new `GemfileLock` updater to bump the Gemfile.lock appropriately similar to other lock file updaters in other strategies.

 **Describe alternatives you've considered**

I looked at using the `extra-files` flag, but since the ruby gem lock file is not a standard format and can't be a template this doesn't seem to be an option.

 **Additional context**

I've started a [fork / branch](https://github.com/googleapis/release-please/compare/main...andrewthauer:release-please:feat-gemfile-lock?expand=1) with what I think might be the appropriate changes. I'm not exactly sure the best way to do a full e2e test atm yet though.

**Comment by schwern** [comment]
I'm having this same problem with every Github release action I've tried.

@andrewthauer Perhaps a simpler and more general approach for release procedures which have to run commands is to allow any commands to be run just before the Release Please changes are committed?

For example...

```
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          run_before_commit: |
            bundle install
```

`bundle install` would be run after Release Please has done its work, but just before it commits and pushes the PR.

**Comment by andrewthauer** [comment]
@schwern - Thanks! Yes a hook before commit would also work. I had to double check, but I didn't see any option that  currently does this. I'm not sure how I would go about adding this atm though. I can dig into the code more unless you can point me in the right direction?

**Comment by schwern** [comment]
@andrewthauer Sorry, I haven't looked at the code. It's just a thought I had.

Hooks would be very useful. In addition to before commit, after commit but before push would also be useful. It could run the code in the Release Please branch with Git configured so one could, for example, update the Gemfile.lock in its own commit.

```
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          before_push: |
            bundle install
            git commit -m 'Update Gemfile.lock'
```

That would be nice because it would separate the Release Please work from the `bundle install` work.
