### ISSUE TITLE
Extra files not honoured for python

### ISSUE THREAD

**Issue by NaffanDroo** [googleapis/release-please#1773]
#### Environment details

  - OS: ubuntu-latest (gh action)
  - Node.js version: Unknown (gh action)
  - npm version: Unknown (gh action)
  - `release-please` version: google-github-actions/release-please-action@v3

#### Steps to reproduce

  1. Set `release-type` to `python`
  2. Define `extra-files` as in the [documentation](https://github.com/marketplace/actions/release-please-action#adding-additional-files)
  3. Example workflow from [this repo](https://github.com/NaffanDroo/tidy-python/blob/main/.github/workflows/release-please.yaml):
  ```yaml
  on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: tidy-python
          extra-files: |
            tests/test_tidy_python.py
            README.md

  ```
  4. The extra files are not properly honoured.
Many thanks!
