### ISSUE TITLE
`draft-pull-request` manifest configuration option doesn't work

### ISSUE THREAD

**Issue by tlaziuk** [googleapis/release-please#1791]
Hello, the `draft-pull-request` manifest configuration option doesn't work, the pull-requests are always created in the `open` state and not in the `draft` state.

Used configuration:
```json
{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "bootstrap-sha": "...",
  "changelog-sections": [
     "...": "..."
  ],
  "plugins": [
    "node-workspace"
  ],
  "draft-pull-request": true,
  "packages": {
     "...": {}
  }
}
```
```yml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          monorepo-tags: true
          changelog-types: '...'
      - ...
```

I think this is a bug, because [the documentation](https://github.com/googleapis/release-please/blob/7526ca8be4fec4d785b44bfb8c8c70078ad7fc73/docs/customizing.md#opening-as-a-draft-pull-request) says it should work.

Thank you in advance for any replies or hints to solve this issue.
