### ISSUE TITLE
Is it possible to configure a release branch name using GitHub actions?

### ISSUE THREAD

**Issue by neptashka** [googleapis/release-please#1807]
Hi! Thank you for this fantastic tool! 

I am using **release-please-actio**n and every time when GitHub bot creates a release PR, the release branch has the same name:
`release-please--branches--master--components--release-please-action`. 
The branch name conflicts with our Jenkins and branching rules.
So my question is: is it possible to configure the branch name, using ${version}, similar to PR-title, or even start the branch name with `release/`?

Here is my release-please.yaml:
```
on:
  push:
    branches:
      master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
```
          
 Will be waiting for your answer!
