### ISSUE TITLE
Maven pom.xml EOF newline getting removed

### ISSUE THREAD

**Issue by jpalomaki** [googleapis/release-please#1894]
Release-please generated GitHub PRs that update `<version />` in a maven project `pom.xml` remove the EOF newline.

See https://github.com/google-github-actions/release-please-action/issues/743 for details.

#### Environment details

  - OS: Ubuntu 22.04
  - Node.js version: 18.15.0
  - npm version: 9.5.0
  - `release-please` version: The one used by https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.5, i.e.`15.8.1`

#### Steps to reproduce

Run a GitHub workflow like so:

```yml
name: release-please

on:
  push:
    branches:
      - master

jobs:
  this:
    runs-on: ubuntu-22.04
    steps:

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: my-package
          token: <github token>
```
