### ISSUE TITLE
How to include generated files in the release-please commit

### ISSUE THREAD

**Issue by rburgst** [googleapis/release-please#1971]
I would like to update the generated documentation which is published via github pages along with every release-please commit.
Checking the customization documentation I only see how to replace version strings, however, it would be nice to not only bump the version in `package.json` etc. but also run a script (i.e. build the docs) and then add those generated files with the version bump commit from release please.

Is this possible?

**Comment by rperryng** [comment]
I have a similar request.

We are using a docs generation tool ([`helm-docs`](https://github.com/norwoodj/helm-docs)) that creates a markdown file with a version badge/image that includes the version string in it, usually sourced from the `Chart.yaml` file, e.g. it generates:

```markdown
![Version: 0.0.1](https://img.shields.io/badge/Version-0.0.1-informational?style=flat-square)
```

I tried to see if I could use the generic parser with the `x-release-please-*` annotations but found it only replaces one version per line.

If I try to be a little cheeky and split up the link into two lines like:

```markdown
<!-- x-release-please-start-version -->
![Version: 0.0.1
](https://img.shields.io/badge/Version-0.0.1-informational?style=flat-square)
<!-- x-release-please-end -->
```

in this particular case it interprets `0.1.1-information` as the version (which makes sense), resulting in something like:

```diff
- ](https://img.shields.io/badge/Version-0.0.1-informational?style=flat-square)
+ ](https://img.shields.io/badge/Version-0.0.2?style=flat-square)
```

which invalidates the image link.  Ideally we could just run our `helm docs ...` command instead after the version was updated.  We are running `release-please` via the GHA so I guess the only solution I can think of here is to:
1. check if a release was cut
2. checkout PR branch
3. run docs generation
4. commit and push

**Comment by fty4** [comment]
@rperryng I have have the same setup and try to use `release-please` and `helm-docs` at the same time.
Also my annotation with `x-release-please-*` only updated one version instead of both.

But I found a solution:
When using helm-docs you can specify your own template ([`README.md.gotmpl`](https://github.com/norwoodj/helm-docs/tree/master#markdown-rendering)) (place it in your chart directory).
When correctly modifing this template you will be able to update the version in both places.

Steps:

1. Use the [default template](https://github.com/norwoodj/helm-docs/blob/3b87f0a6454b2f562aca410f62bb4f8d79507db1/pkg/document/template.go#L19-L37)
1. Resolve the [_badgesSection_](https://github.com/norwoodj/helm-docs/blob/3b87f0a6454b2f562aca410f62bb4f8d79507db1/pkg/document/template.go#L96-L103) with the templated content
1. Resolve the [_versionBadge_](https://github.com/norwoodj/helm-docs/blob/3b87f0a6454b2f562aca410f62bb4f8d79507db1/pkg/document/template.go#L66-L74) with the templated content
1. Set the [style](https://github.com/norwoodj/helm-docs/blob/3b87f0a6454b2f562aca410f62bb4f8d79507db1/pkg/document/template.go#L70) fix to your preference (e.g. `flat-square`)
1. Create a variable (`chartVersion`) for the version and use it instead of the `.Version` variable
1. Set the [`x-release-please-version`](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) tag to the variable (as gotmpl comment)

A the end you will be presented with the following template:

```gotmpl
{{- $chartVersion := "0.1.0" -}}{{- /* x-release-please-version */ -}}
{{ template "chart.header" . }}
{{ template "chart.deprecationWarning" . }}

![Version: {{ $chartVersion }}](https://img.shields.io/badge/Version-{{ $chartVersion | replace "-" "--" }}-informational?style=flat-square)
{{ template "chart.typeBadge" . }}
{{ template "chart.appVersionBadge" . }}

{{ template "chart.description" . }}

{{ template "chart.homepageLine" . }}

{{ template "chart.maintainersSection" . }}

{{ template "chart.sourcesSection" . }}

{{ template "chart.requirementsSection" . }}

{{ template "chart.valuesSection" . }}

{{ template "helm-docs.versionFooter" . }}
```

When adding this file via [`extra-files`](https://github.com/google-github-actions/release-please-action/#configuration) to release-please-action the PR will also update the version in the template:

```yaml
    - uses: google-github-actions/release-please-action@v3
      with:
        extra-files: README.md.gotmpl
```

Because then only the gotmpl-file will be templated the helm-docs workflow needs to be triggered again.
Therefore I not only trigger the helm-docs on the PR trigger but also as last step of the release wf.
With this the release PR created from release-please-action will be extended by a new commit with the updated version in the README.md.

<hr />

To see how the workflows are connected to each other you can view them here:

<details>

<summary>.github/workflows/helm-docs.yml</summary>

```yaml
name: Helm docs
on:
  pull_request:
    paths:
    - "charts/**"
    - ".github/**"

  # workflow_call is used to trigger workflow from release-please-action PRs
  # The automated PR from the rpa will NOT trigger ci runs - therefore this
  # wf will be triggered manually from the release wf.
  workflow_call:
    inputs:
      branchName:
        required: true
        type: string

permissions:
  contents: write # to push commit to PR branch

jobs:
  helm-docs:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # if triggered from workflow_call checkout branch
      with:
        ref: ${{ inputs.branchName }}

    - uses: gabe565/setup-helm-docs-action@531285940659679b5e1c3a41aa0c89d080f5f6b4 # v1.0.2

    - name: Generating Helm docs
      shell: bash
      run: helm-docs

    - name: Commit and push to pull request
      uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
      with:
        commit_message: |
          docs(helm): update Helm chart README

          This is an automatic commit due to changes to the chart value files.
          This change reflects the changes to the README.md of the chart.

        file_pattern: 'charts/**/README.md'
```

</details>

<details>

<summary>.github/workflows/release.yml</summary>

```yaml
name: Chart Release
on:
  push:
    branches:
    - main
    paths:
    - "charts/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  changed-charts:
    name: Release chart

    permissions:
      contents: write
      packages: write
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0

    - uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      # create list of chart names (without path) readable for GH matrix wf
    - name: check changed charts
      id: cc
      shell: bash
      run: |
        MATRIX=$(ct list-changed \
          --target-branch main \
          --since '${{ github.event.before }}'  \
          | sed 's/^charts\///g' \
          | tr '\n' ' ' \
          | xargs \
          | sed 's/ /",&"/g' )

        if [ -z "$MATRIX" ]
        then
          echo "No charts changed"
          exit 0
        fi

        # add JSON array brackets
        MATRIX="[\"${MATRIX}\"]"

        echo "changed_charts_matrix=${MATRIX}"
        echo "changed_charts_matrix=${MATRIX}" >> "$GITHUB_OUTPUT"
    outputs:
      changed_charts_matrix: ${{ steps.cc.outputs.changed_charts_matrix }}

  release-chart:
    needs: changed-charts
    if: ${{ needs.changed-charts.outputs.changed_charts_matrix }}
    runs-on: [self-hosted]
    strategy:
      matrix:
        changed_chart: ${{ fromJSON(needs.changed-charts.outputs.changed_charts_matrix) }}
    outputs:
      # if PR is created from rpa output branch name to trigger helm docs wf
      rpaHeadBranchName: ${{ steps.job-output.outputs.headBranchName }}
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: google-github-actions/release-please-action@v3
      id: rpa
      with:
        # include gotmpl to update version in chart README
        extra-files: README.md.gotmpl
        release-type: helm
        package-name: ${{ matrix.changed_chart }}
        path: charts/${{ matrix.changed_chart }}
        monorepo-tags: true
        changelog-types: >
          [
            { "type": "feat", "section": "Features" },
            { "type": "fix", "section": "Bug Fixes" },
            { "type": "revert", "section": "Reverts" },
            { "type": "chore", "section": "Miscellaneous Chores" },
            { "type": "docs", "section": "Documentation" },
            { "type": "test", "section": "Tests", "hidden": "true" },
            { "type": "ci", "section": "Continuous Integration", "hidden": "true" }
          ]

    - name: output rpa headBranchName if present
      id: job-output
      shell: bash
      run: |
        RPA_PR_JSON='${{ steps.rpa.outputs.pr }}'

        headBranchName=$(echo $RPA_PR_JSON | tr -d '\n' | jq -r '.headBranchName')
        if [ "${headBranchName}" ]; then
          echo "::debug::Found headBranchName"
          echo "headBranchName=${headBranchName}" >> "$GITHUB_OUTPUT"
        else
          echo "::debug::NO headBranchName found"
        fi

    - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      if: ${{ steps.rpa.outputs.releases_created }}
      with:
        version: v3.13.2

    - name: Push OCI Helm chart
      # hidden

  helm-docs-release-pr:
    name: Helm docs for release PR
    needs: release-chart
    uses: ./.github/workflows/helm-docs.yml
    if: ${{ needs.release-chart.outputs.rpaHeadBranchName != '' }}
    with:
      branchName: ${{ needs.release-chart.outputs.rpaHeadBranchName }}
```

</details>

<hr />

Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))
