### ISSUE TITLE
Add .deb to extra-files ?

### ISSUE THREAD

**Issue by ParoaPe** [googleapis/release-please#1995]
Hello, It is possible to add .deb to extra-files ?

I already try to add .deb in release-please with my workflow but no extra-files was append (and no errors):

```yml
# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - main

jobs:
  release-please: 
    permissions:
        contents: write
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Depends install
        run: sudo apt-get install -y dpkg-dev

      - name: Create folder package
        run: mkdir package

      - name: Copy files (with exclusions)
        run: rsync -av --exclude=README.md . package/

      - name: Create .deb
        run: dpkg-deb --build package

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          default-branch: main
          extra-files: |
          package.deb
```
