### ISSUE TITLE
Failure to read config file from `.github/workflows/`

### ISSUE THREAD

**Issue by elijaholmos** [googleapis/release-please#2026]
#### Environment details

  - OS: Same as specified in https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.11
  - Node.js version: Same as specified in https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.11
  - npm version: Same as specified in https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.11
  - `release-please` version: Same as specified in https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.11

#### Steps to reproduce

  1. Create a workflow file which uses the release-please action
```yml
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: google-github-actions/release-please-action@v3
              with:
                  command: manifest
                  config-file: .github/workflows/config/release-please-config.json
                  manifest-file: .github/workflows/config/.release-please-manifest.json
```
  2. Set the `config-file` and `manifest-file` to locations inside of the `.github/workflows` directory
  3. Trigger the action
  4. Observe the action logs:
```
Run google-github-actions/release-please-action@v3
  with:
    command: manifest
    config-file: .github/workflows/config/release-please-config.json
    manifest-file: .github/workflows/config/.release-please-manifest.json
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    changelog-host: https://github.com/
    github-api-url: https://api.github.com/
    github-graphql-url: https://api.github.com/graphql
    monorepo-tags: false
❯ Fetching .github/workflows/config/release-please-config.json from branch main
❯ Fetching .github/workflows/config/.release-please-manifest.json from branch main
✔ Building releases
...
✔ updating from 0.1.1 to 0.1.1
⚠ file changelog.json did not exist
❯ Fetching changelog.json from branch main
❯ Fetching .github/workflows/config/.release-please-manifest.json from branch main
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "cd7f677660dbeeef4e44311bb16bf820477cdcc1".
✔ Successfully created branch at https://api.github.com/repos/elijaholmos/ci-cd-playground/git/refs/heads/release-please--branches--main--components--test
✔ Got the latest commit tree
Error: release-please failed: Error adding to tree: cd7f677660dbeeef4e44311bb16bf820477cdcc1
```

This error goes away if I relocate the config files to any directory outside of the `.github/workflows` directory.

For more information, view [this repo](https://github.com/elijaholmos/ci-cd-playground/actions/runs/5651108914/job/15308639937).
