### ISSUE TITLE
Setting `changelog-type` to "github" results in a new release on any type of commit

### ISSUE THREAD

**Issue by bodgit** [googleapis/release-please#2096]
#### Environment details

  - OS: LInux
  - Node.js version: n/a
  - npm version: n/a
  - `release-please` version: Using v3 of the release-please-action so whatever version is used there.

#### Steps to reproduce

See #2078 for the background. I found that with any type of commit/merged PR, release-please was generating a new release, even for just chore commits, which I thought shouldn't happen.

My `release-please-config.json` was originally this:
```json
{
  "changelog-type": "github",
  "packages": {
    ".": {
      "release-type": "go",
      "extra-files": [
        "README.md",
        "main.go"
      ]
    }
  }
}
```
I had added the `changelog-type` setting to see what the difference was in the generated changelog, removing it so my `release-please-config.json` looks like this:
```json
{
  "packages": {
    ".": {
      "release-type": "go",
      "extra-files": [
        "README.md",
        "main.go"
      ]
    }
  }
}
```
And now normal behaviour is restored.

**Comment by stutommi** [comment]
I'm puzzled by the same issue, I can see that with the configuration (below), seems like atleast commits starting with "chore" and "docs" (and probably all the others aswell, haven't tested) result in release-please action generating patch bumps:

```yml
name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          release-type: go
          bump-minor-pre-major: true
          changelog-types: >
            [
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "ci", "section": "Continuous Integration", "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "revert", "section": "Reverts", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]
```
