### ISSUE TITLE
Simple strategy ignores version.txt

### ISSUE THREAD

**Issue by GeorgeSixth** [googleapis/release-please#2098]
- What you're trying to do: I have a C++ project running using github actions and cmake to compile a library. I am now trying to add release please to facilitate the whole process. I am using the `simple` strategy and give it a `version.txt` as specified in the example repository linked on the release-please readme page.
 
- What code you've already tried:
release-please.yml
```
name: Release-Please
on:
  push:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: [REDACTED]
        with:
          app_id: ${{ secrets.GH_ACTION_APP_ID }}
          private_key: ${{ secrets.GH_ACTION_APP_KEY }}

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          token: ${{ steps.generate_token.outputs.token }}
          default-branch: main
          bump-minor-pre-major: true
          include-v-in-tag: false
          pull-request-header:
            ":star: I have created a release :star:"
          changelog-types: |
            [
              {"type":"feat","section":"🚀 Features","hidden":false},
              {"type":"fix","section":"🐞 Bug Fixes","hidden":false}
            ]
```

My version.txt is rather simple:
```
0.0.1
```

Is there something I am missing in regards to the strategy ? I want it to create the 0.0.1 version but it's ignored no matter what I try or do in the .yml file it's ignored.
Thank you for taking the time to read and answer !
