### ISSUE TITLE
How to use extra-files?

### ISSUE THREAD

**Issue by regseb** [googleapis/release-please#2135]
I'm trying to use _Release Please_ to create a release of my WebExtension. I need to update the version number in `package.json`, `package-lock.json` and also `src/manifest-chromium.json` and `src/manifest-chromium.json`.

- I use _Release Please Action_:

  ```yaml
  name: Release
  on:
    push:
      branches: [main]

  jobs:
    release-please:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: write
      steps:
        - name: Run Release Please
          uses: google-github-actions/release-please-action@v3
          with:
            command: manifest-pr
  ```

- With `.release-please-manifest.json`: `{}`
- And `release-please-config.json`:

  ```yaml
  {
    "packages": {
      ".": {
        "release-type": "node",
        "extra-files": [
          {
              "type": "json",
              "path": "webext/manifest-chromium.json",
              "jsonpath": "$.version"
          }, {
              "type": "json",
              "path": "webext/manifest-firefox.json",
              "jsonpath": "$.version"
          }
        ]
      }
    }
  }
  ```

But the `package.json` and `package-lock.json` files are not updated. And only the formatting is changed in `manifest-*.json` files. https://github.com/regseb/testcase/pull/6

How can I add two files to a Node project release (which isn't monorepo)?
