### ISSUE TITLE
Configuration "extra-files" and "changelog-type" not working.

### ISSUE THREAD

**Issue by origin-coding** [googleapis/release-please#2138]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
- What code you've already tried
- Any error messages you're getting

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I'm using release-please for automatically release, and I want to set "changelog-type" to "github" for having a GitHub-styled changelog.
Besides, I also want to update my Cargo.toml file in src-tauri.

Here is my directory:
![Directory](https://github.com/googleapis/release-please/assets/52844714/0df0932f-99b5-496c-be4c-a613f3454489)

Here is my GitHub actions workflow and configuration files.
```yaml
jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
```

```json
{
  "changelog-type": "github",
  "packages": {
    ".": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "node",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false,
      "changelog-type": "github",
      "extra-files": [
        {
          "type": "toml",
          "path": "src-tauri/Cargo.toml",
          "jsonpath": "$.version"
        }
      ]
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}

```

But my pull request doesn't update my Cargo.toml file and it doesn't modify my changelog type as expected, it looks like this:
![Pull request](https://github.com/googleapis/release-please/assets/52844714/3af0202d-e552-468d-abfb-de0faa73dc37)

So could you please help me on this?
