### ISSUE TITLE
Include v prefix in extra-files

### ISSUE THREAD

**Issue by krak3n** [googleapis/release-please#2160]
Hi

I have a `yaml` file I would like to bump in the `extra-files` config like this:

```json
{
  "release-type": "go",
  "packages": {
    ".": {}
  },
  "extra-files": [
    "version.go",
    {
      "type": "yaml",
      "path": "buf.plugin.yaml",
      "jsonpath": "$.plugin_version"
    }
  ]
}
```

This needs to include a `v` prefix on the version but I cannot see a configuration option to be able to set that. The yaml it generates is:

```yaml
version: v1
 name: plugin-name
 plugin_version: 1.0.0
 source_url: https://github.com/repo-url
 output_languages:
   - go
```

For `buf.build` this is not a valid semantic version as it does not include the `v` prefix and so the pushing of the plugin is rejected.

What I would like release please to generate is this:

```yaml
version: v1
 name: plugin-name
 plugin_version: v1.0.0
 source_url: https://github.com/repo-url
 output_languages:
   - go
```

Is this possible?

**Comment by chingor13** [comment]
Using the [`GenericYaml` updater](https://github.com/googleapis/release-please/blob/main/src/updaters/generic-yaml.ts), it is not possible to include the `v` in the string. It might be possible to add an option to it to allow adding the `v`.

As a workaround, you can use a plain [`Generic` updater](https://github.com/googleapis/release-please/blob/main/src/updaters/generic.ts) which uses annotations in code. It will look for a semver-like string and replace that part, leaving the remaining text around it untouched. To use this, just pass the file path (like you have for `version.go`) to `extra-files` rather than the json object config.

You could do something like:
```yaml
version: v1
 name: plugin-name
 plugin_version: v1.0.0 # x-release-please-version
 source_url: https://github.com/repo-url
 output_languages:
   - go
```
