### ISSUE TITLE
How to use `x-release-please-version` for different components in the same file (with `extra-files`) 

### ISSUE THREAD

**Issue by 1aziz** [googleapis/release-please#2175]
Is there any way to use the same `extra-files` functionality for multiple components? 

For example, I've got the following packages in my `release-please-config.json`:

```json
  "packages": {
    "packages/elk/deploy/helm": {
      "extra-files": [
        "/packages/versions.yaml"
      ]
    },
    "packages/eso/deploy/helm": {
      "extra-files": [
        "/packages/versions.yaml"
      ]
    },
    "packages/test/deploy/helm": {}
  },
```
As you can see, I'd like to update the versions of `eso` and `elk` (different versions) to be updated in the `versions.yaml` file each time a release PR gets opened for these components. 

However, by default, each release PR updates _all_ versions to the same. 

My `/packages/versions.yaml`: 

```yaml
---
packages:
  elk: 1.0.28 # x-release-please-version
  eso: 1.2.28 # x-release-please-version
```
