### ISSUE TITLE
Release Please cannot parse version string

### ISSUE THREAD

**Issue by oakyydev** [googleapis/release-please#2204]
### What you're trying to do
I am trying to setup release please to create releases for the beta as well as the production branch. I have setup two workflows for both branches. But every time I try to push to my branch I get the following error: `release-please failed: unable to parse version string: 0.1`

### What code you've already tried
**release-beta.yml**
```
on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    name: Create Beta Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please-beta
        with:
          target-branch: beta
          token: ${{ secrets.GH_TOKEN }}
          manifest-file: .release-beta-manifest.json
          config-file: release-beta-config.json

```
**release-beta-config.json**
```
{
    "packages": {
        ".": {
            "bootstrap-sha": "230495319f1b508757dd86d97565e8fb1e43f4de",
            "release-type": "php",
            "prerelease-type": "beta",
            "prerelease": true,
            "skip-github-release": true,
            "release-as": "1.0.0"
        }
    },
    "plugins": [
        {
            "type": "sentence-case"
        }
    ]
}
```
**release-beta-manifest.json**
```
{
    ".": "0.0.0"
}
```
**Workflow output**
[github_workflow_output.txt](https://github.com/googleapis/release-please/files/14076201/github_workflow_output.txt)

### Any error messages you're getting
So far I only got this error `Error: release-please failed: unable to parse version string: 0.1`

I'm sorry if this issue is explained somewhere but I couldn't find any solution even in the issues or in the repo for Github Actions of release-please.
