### ISSUE TITLE
Difference between 'release-please-config.json' and '.release-please-manifest.json'?

### ISSUE THREAD

**Issue by linrongbin16** [googleapis/release-please#2237]
I am trying to use release-please with below options:

* release-type: `'simple'`
* package: `'.'`
* package-name: `'ci-template.nvim'`

And I just want to package all the things in whole repo.

After read the docs: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md, I am confused.

1. It looks like the two config files 'release-please-config.json' and '.release-please-manifest.json' use exactly same schema?
2. What's the difference between them? 
3. Do I have to specify both of them?

Currently I am configure it like:

### ci.yml

```yaml
jobs:
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
```

please see: https://github.com/linrongbin16/ci-template.nvim/blob/7a6e557be64795342d69e208710be9db91789073/.github/workflows/ci.yml#L139-L142

### release-please-config.json

```json
{
  "release-type": "simple",
    "packages": {
      ".": {
        "package-name": "ci-template.nvim"
      }
  }
}
```

please see: https://github.com/linrongbin16/ci-template.nvim/blob/7a6e557be64795342d69e208710be9db91789073/release-please-config.json
