### ISSUE TITLE
Manifest release is releasing the entire repo

### ISSUE THREAD

**Issue by userbradley** [googleapis/release-please#2276]
Hello,

I am following the documentation for manifest release, but when downloading the generated assets for a release, the entire repo is being included in the assets

This is the layout of the repo

```text
.
├── helm-charts
│   ├── airflow-workload-id
│   │   ├── CHANGELOG.md
│   │   ├── Chart.yaml
│   │   ├── README.md
│   │   ├── README.md.gotmpl
│   │   ├── Taskfile.yaml
│   │   ├── templates
│   │   └── values.yaml
│   ├── codesearch
│   │   ├── Chart.yaml
│   │   ├── README.md
│   │   ├── README.md.gotmpl
│   │   ├── Taskfile.yaml
│   │   ├── templates
│   │   └── values.yaml
│   └── gcs-web-server
│       ├── CHANGELOG.md
│       ├── Chart.yaml
│       ├── README.md
│       ├── README.md.gotmpl
│       ├── Taskfile.yaml
│       ├── templates
│       └── values.yaml
└── release-please-config.json

8 directories, 18 files

```

And the below config files

```json
# .release-please-manifest.json`
{
  "helm-charts/airflow-workload-id": "1.1.0",
  "helm-charts/gcs-web-server": "1.0.0",
  "helm-charts/codesearch": "1.0.0",
}
```

and

```json
# release-please-config.json
{
  "bootstrap-sha": "d50c1d3d59ab955ab8b0330131c22790d8acbf1b",
  "packages": {
    "helm-charts/airflow-workload-id": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "helm",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false
    },
    "helm-charts/codesearch": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "helm",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false
    },
    "helm-charts/gcs-web-server": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "helm",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

And below is the GitHub action I am using 

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
```

I am trying to get something like https://github.com/Financial-Times/origami where each package is released as it's own thing, and the assets associated with that release are only in that folder

I'm not sure where I've gone wrong, or if this is the expected behaviour?

Docs followed: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
