### ISSUE TITLE
How would i update the image tag using extra-files

### ISSUE THREAD

**Issue by stecullum** [googleapis/release-please#2340]
Using extra-files how can i update the tag value for an image with a prefix eg "app-0.0.1"
 
 Thanks
    
```json
"packages": {
    "app": {
      "release-type": "simple",
      "package-name": "app",
      "extra-files": [
        {
          "type": "yaml",
          "path": "test.yaml",
          "jsonpath": "$./spec/values/image/tag.version"
        }
      ]
    },
 ```
 
 and the target of..
 ```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  values:
    replicaCount: 1 # there is only ever one allowed to run at once 
    image:
      name: "app"
      tag: "app-0.0.0"
 ```
