### ISSUE TITLE
Expose the version / tag that will be generated in the PR json

### ISSUE THREAD

**Issue by stecullum** [googleapis/release-please#2341]
Can you consider outputting the release version info that the PR will create  in the `pr json`.  

This opens up the opportunity to do any kind of extra file manipulation..  for example...

In a github action.. We can update the PR files with any additional infor we want for example... 
```yaml
   - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json

  ## we have just created a PR now modify it however we want eg.. replace the image tag in a k8s manifest
  - name: Modify pull-request files after RP
    if: steps.release.outputs.prs_created == 'true'. 
    uses: jaywcjlove/github-action-modify-file-content@main
    with:
      branch: ${{ fromJson(steps.release.outputs.pr).headBranchName }}
      body: "{{ fromJson(steps.release.outputs.pr).version }} .. **I didnt see it in json**
      path: 'deployment.yaml'
```

Thanks
