### ISSUE TITLE
Version bump to dependencies(package.json), root package-lock.json

### ISSUE THREAD

**Issue by iamzaker** [googleapis/release-please#2425]
I was following the [Manifest Driven release-please
](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#manifest-driven-release-please)
- What you're trying to do
  I am trying to create a Github release, changelog generation, version bumps to changed packages, dependent projects & finally a npm publish
- What code you've already tried
  I have the below code for `release-please-config.json`
```
{
    "include-component-in-tag": true,
    "include-v-in-tag": true,
    "tag-separator": "@",
    "separate-pull-requests": true,
    "packages":{
        "packages/hello-world-util": {                       
            "release-type": "node",            
            "always-link-local": true,
            "changelog-path": "CHANGELOG.md",
            "path": "packages/hello-world-util",
            "versioning-strategy": "auto",
            "intial-version": "0.0.1",
            "plugins":[
                {
                    "type": "node-workspace",
                    "updateAllPackages": true,
                    "updatePeerDependencies": true,
                    "considerAllArtifacts": true
                }
            ]
        },
       "starters/nestjs-startup-app": {
            "always-link-local": true,
            "path": "starters/nestjs-startup-app",
            "skip-github-release": true,
            "plugins":[
                {
                    "type": "node-workspace",
                    "updateAllPackages": true,
                    "updatePeerDependencies": true,
                    "considerAllArtifacts": true
                }
            ]
       }
    },
    "plugins": ["linked-versions"],
    "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
  }
```
Not sure if I have to use both plugins but either of them would work if tried independently with other changes in configuration.

The `release-please-manifest.json` with versions:
```code
{
    ".": "0.0.1",
    "packages/hello-world-util": "0.0.1"
}
```
A minimal code describing the `workflow` `step` to release github notes, changelogs
```
jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: googleapis/release-please-action@v4
          id: release
          with:
            release-type: node
            config-file: release-please-config.json
            manifest-file: .release-please-manifest.json
            path: | 
                packages/hello-world-util
```
  
- Any error messages you're getting
  I don't see any error message though, but was looking a way to auto update the root `package-lock.json`,  other project dependencies, the above configuration creates a pr with changelog, version bump in `hello-world-util` `package` but I was looking if it can also update the dependent packages, for eg: `nestjs-startup-app` has dependency on `hello-world-util` also, there is a single `package-lock.json` at root level if I can update it somehow.
