### ISSUE TITLE
Using a jsonpath array filter with GenericToml extra-file config does not find the relevant version

### ISSUE THREAD

**Issue by roberthjaplaio** [googleapis/release-please#2455]
I have a python project managed with uv where I specify a build system in the pyproject.toml file. When I do this, my application is "installed" into the environment and I receive a version number into the uv.lock file. 

While updating a lock file generally is perhaps not my best idea, I decided to try it out anyway using the generic toml updater but it seems I am unable to use a jsonpath filter. I have verified that the jsonpath works when I convert the toml to json, but to my surprise the release-please cli and the release please github action both log out that nothing was found in the uv.lock file. (`No entries modified in $.package[?(@.name==="app")].version`)

I have tried specifying an absolute path from the root of the project ("/uv.lock"). I have tried escaping double quotes as well as using single quotes, I've tried == and === but no success. 

Example minimum uv.lock file to reproduce:

```
version = 1
requires-python = ">=3.13"

[[package]]
name = "app"
version = "3.1.0"
source = { virtual = "." }
```

#### Environment details

  - OS: happens on OSX 15 and also the github action (v4)
  - Node.js version: 23.4.0
  - npm version: 10.9.2
  - `release-please` version: 16.15.0

#### Steps to reproduce

  1. using a release please config similar to this one:
  ```
  {
  "release-type": "python",
  "packages": {
    ".": {
      "extra-files": [
        {
          "type": "toml",
          "path": "uv.lock",
          "jsonpath": "$.package[?(@.name==\"app\")].version"
        }
      ]
    }
  }
}
```

Other attempted jsonpaths:
```
$.package[?(@.name==\"app\")].version
$.package[?(@.name=='app')].version
$.package[?(@.name===\"app\")].version
$.package[?(@.name==='app')].version
```

  2.  run release-please using cli or in a github action

I understand my problem could be avoided through various means and supporting updating a lock file like this makes no sense for release-please. However it seems that the generic toml updater might be broken because this file is a valid toml file and does not get updated.

**Comment by ClaytonJY** [comment]
I'm struggling with the same issue in trying to combine `uv` and `release-please`.

It's unfortunate `uv` records the version of editable dependencies in the lockfile, and that [could change](https://github.com/astral-sh/uv/issues/7533), but until it does I'm not sure how to workaround this.

My hope was to do as OP tried, using `extra-files`, but I'm having the same issue where it seems the full JSONPath specification might not be supported by `release-please`? If that's true, I think this should be reflected in [the docs](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-json-files), which does not currently indicate any known restrictions.

Other approaches I can think of for `uv` + `release-please`:
1. use dynamic versioning with build-time hatchling hooks as [recommended here](https://github.com/astral-sh/uv/issues/7533#issuecomment-2555313297). I haven't tried this, and I don't have any need for a built package (I'm shipping docker containers), so I don't want to introduce a build step, but seems like a nice solution when you're already building w/ hatchling
2. run `uv sync` in the same github workflow that runs `release-please`, committing the changed `uv.lock` to the same release branch created by `release-please`. I don't know for sure that this would work, but I think it _should_?
3. don't version the python package at all. Set version to something like `0.0.0`, never update it. Use `release-please` to version the higher-level artifact, e.g. the tag on the docker container in my case. This seems pretty reasonable! Especially since there can be changes to the container unrelated to the python code, like changes to the Dockerfile. Why version both if I'm only shipping the container, right?

Option 3 is probably best for my use-case (only ship containers, not python packages), though I'll report back if it falls short. Curious to hear how others are working around this today.

**Comment by ClaytonJY** [comment]
I ended up doing option 2 instead, so I could have a good version available in my application for logging purposes. Was easy enough:

<details>

```yaml
jobs:
  release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Create PR with release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        # with:
          # will need a PAT to trigger checks from release-please PRs
          # https://github.com/googleapis/release-please-action?tab=readme-ov-file#github-credentials
          # token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # release-please is unable to update uv.lock, so we do it ourselves

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}

      - name: Setup `uv`
        uses: astral-sh/setup-uv@v5

      - name: Update `uv.lock`
        run: |
          uv lock
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uv.lock
          git commit -m "ci: update uv.lock"
          git push
```

</details>

Still very interested to better understand the limits of JSONPath in release-please!
