### ISSUE TITLE
release-please does not handle the case where code-suggester returns 0 from createPullRequest

### ISSUE THREAD

**Issue by bewinsnw** [googleapis/release-please#2551]
This issue was originally reported in https://github.com/googleapis/release-please/issues/1955 but then closed. However, the bug is easily traceable in the code.

The issue manifests as a "Not Found" error (with no other explanation) when running release-please-action; more details on that here https://github.com/googleapis/release-please-action/issues/840 . Commenters there traced it down to a call being made to `https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/pulls/0`. release-please-action does not make any calls to pulls itself, but just wraps release-please.

So why would release-please request PR 0? The only call for a GET of a PR in release-please is here https://github.com/googleapis/release-please/blob/422df5a6a9d44a52c6c682563d1795b8fd246215/src/github.ts#L1179 which is called from this code: https://github.com/googleapis/release-please/blob/422df5a6a9d44a52c6c682563d1795b8fd246215/src/github.ts#L1155-L1169

So, we would request PR 0 if `createPullRequest` returns 0; that function is in `code-suggester` over here: https://github.com/googleapis/code-suggester/blob/6600a47461f0f027bf7b49671139456dfa4a5b4d/src/index.ts#L122-L127 - it does it whenever the changeset is empty.

It would be more informative if `release-please` checked the PR number returned by `createPullRequest` and if it is 0, warn that the changeset was empty and return, instead of going on to make the GET call that errors out.

#### Environment details

  - OS: ubuntu 24
  - Node.js version: 20
  - npm version: n/a (gh runner)
  - `release-please` version: 16.18.0

#### Steps to reproduce

See also the two bugs linked above; in my case I saw it on merge of this workflow to main:
```
name: Release, please!
on:
  push:
    branches:
      - main
      - master
concurrency:
  group: release-please
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Get token to create pull request
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: simple
```

and a .release-please-manifest.json of
```
{".": {"file": "version.txt"}}
```
(version.txt was renamed from VERSION in the same commit)

It's unclear to me how the changeset is empty, but it doesn't matter much since the bug is obvious looking at https://github.com/googleapis/release-please/blob/422df5a6a9d44a52c6c682563d1795b8fd246215/src/github.ts#L1155-L1169
