### ISSUE TITLE
Support initial development phase (aka Major version zero)

### ISSUE THREAD

**Issue by jcornaz** [googleapis/release-please#558]
**Is your feature request related to a problem? Please describe.**
I have software in the [initial development phase](https://semver.org/#spec-item-4), and would like to cut releaseses with a major version zero.

 **Describe the solution you'd like**
If the major component of my current version is `0`, `release-please` could:
* bump the patch component for features and fixes. (example: `0.1.2` -> `0.1.3`)
* bump the minor component for breaking changes. (example: `0.1.2` -> `0.2.0`)
* (as a consequence) never bumps the major component.

Of course there will be a time where I'll eventually want to bump to `1.0.0`. In order to let release-please that I'm ready for the big "one dot oh" there could be a flag for the release-please CLI, and option for the github action.

 **Describe alternatives you've considered**
Use release-please only for the changelog generation and always manually override the version numbers. But this is quite error prone, and maybe not using release-please would be a better solution. :-/

 **Additional context**
I would like to raise two arguments in favor of this:

1. Initial development phase is part of the semver specification: https://semver.org/#spec-item-4
2. In rust, for example, there are explicit quality standards for libraries that may "force" people to release their library with a major version zero (under special conditions): https://rust-lang.github.io/api-guidelines/necessities.html#c-stable

**Comment by bcoe** [comment]
@jcornaz I think you should get the behavior you want if you use the setting `--bump-minor-pre-major`, at which point you can put the footer:

```
Release-As: v1.0.0
```

In a commit message when you're ready to move from `0.x.x` to `1.x.x`.

**Comment by jcornaz** [comment]
Thanks @bcoe, that sounds like what I am looking for indeed. Just two more questions:

1. Is it possible when using the github action?
2. Is it documented somewhere?

**Comment by jcornaz** [comment]
Never mind, I found the documentation for the github action: https://github.com/GoogleCloudPlatform/release-please-action#configuration

Thanks @bcoe for the support.

**Comment by jcornaz** [comment]
Acutally, it doesn't work. @bcoe Do you mind pointing what is wrong in my setup?

```yml
name: Release

on:
   push:
      branches:
      - main

jobs:
   release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: GoogleCloudPlatform/release-please-action@v2.4.2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: simple
            package-name: hello-world
            bump-minor-pre-major: Yes
```
