### ISSUE TITLE
github-release node monorepo package: no recent release PRs found

### ISSUE THREAD

**Issue by joeldodge79** [googleapis/release-please#668]
Using the release-please-action a release pr is created and appropriately updated. However, once it's merged the workflow logs `no recent release PRs found`

config:
```
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           monorepo-tags: true
           # tried with and w/out package-name
           # package-name: '@looker/sdk'
           path: packages/sdk/
```
