### ISSUE TITLE
GitHub action not run on release published

### ISSUE THREAD

**Issue by P4sca1** [googleapis/release-please#766]
I use https://github.com/google-github-actions/release-please-action and it successfully generates a GitHub release once the release PR gets merged.
However I have a second GitHub action which builds and deploys my apps and runs whenever a new release gets published. This action worked fine when manually creating releases or when the tool lerna created the releases automatically.
For some reason it does not work for automatically generated releases from `release-please`.

```yml
name: Build, publish and deploy apps

on:
  release:
    types:
      - published

jobs:
  build-publish-deploy:
```
