### ISSUE TITLE
Unhelpful "not found" message when running on private repo

### ISSUE THREAD

**Issue by nzakas** [googleapis/release-please#772]
#### Environment details

  - OS: Ubuntu 18.04.5 (GitHub Workflow)
  - Node.js version: n/a
  - npm version: n/a
  - `release-please` version: v1.3.0

#### Steps to reproduce

  1. Use the sample `release-please.yml` workflow from the README in a private Node.js repository that has had zero releases so far.
  2. Push a commit to the repository.
  3. Get this output:

```
Run GoogleCloudPlatform/release-please-action@v1.3.0
✖ no recent release PRs found
✔ found 6 commits since undefined
✖ branch release-v1.0.0 already exists
✖ CHANGELOG.md not found
✔ creating CHANGELOG.md
✔ updating package.json from 0.0.0 to 1.0.0
✔ updating package-lock.json from 0.0.0 to 1.0.0
✖ file samples/package.json did not exist
Error: release-please failed: Not Found
```

What does that last "Not Found" mean?

**Comment by bcoe** [comment]
@nzakas could I bother you to try running `release-please@v2`, just to see if we're still having the same issue?

**Comment by nzakas** [comment]
When I flipped the repo public, the problem went away: https://github.com/humanwhocodes/memory

**Comment by bcoe** [comment]
@nzakas sounds like if was likely a permission issue on private repositories.

**Comment by rudywaltz** [comment]
this is possible still issue with latest version google-github-actions/release-please-action/issues/262
on my private repo I didn't see this issue, but within the organisation repo I have the same with the latest version

**Comment by bcoe** [comment]
@rudywaltz sounds like permission issues, what we can improve is the quality of that error message (which is actually in one of our dependencies I believe).

**Comment by bcoe** [comment]
@rudywaltz if you have the cycles, perhaps you could run the CLI version of `release-please` with `--debug` and see if anything jumps out? (it might work because of the different type of token).

**Comment by rudywaltz** [comment]
Sadly I think we found the issue our GitHub token was rotated. Just it was too much coincident.
(We use a unique token because we triggering another Action after.

**Comment by bcoe** [comment]
_@chingor13 assigning this one over to you, not out of SLO for a month or so._

We could perhaps address this issue when we address https://github.com/googleapis/repo-automation-bots/issues/1636.

**Comment by abeMedia** [comment]
I'm having a similar issue. It creates the release PR without a problem, but then when I merge that I get the same message when it's meant to create the releases:

![image](https://user-images.githubusercontent.com/4355715/126853621-6e00823c-91fb-4b74-bcd4-d4abea99ead1.png)

This only seems to be happening on free orgs as I did the same setup on a paid one just earlier today and it worked fine.

**Comment by bcoe** [comment]
@abeMedia @nzakas I'm testing on a private repository, using the default `GITHUB_TOKEN`, with the latest version of `release-please`, and I can't seem to get this `Not found` error, I'm using this configuration:

```yml
  on:
    push:
      branches:
        - main
  name: release-please
  jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: GoogleCloudPlatform/release-please-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: go
            package-name: release-please-action
            monorepo-tags: false
            bump-minor-pre-major: false
            clean: true
            fork: false
            pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
```
